name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 195.35.49.146
          port: 65002
          username: u101819766
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            cd domains/egyrus.ru/public_html
            git pull origin main
